language: node_js

# test on two node.js versions: 0.10
node_js:
  - 10
  
services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_script:
  - npm run-script coveralls